@extends('layouts.masterpage')

@section('seo')
    <title>GameFun | Terms Conditions</title> 
    <meta name="description" content="This is gaming zone website where all type of games are display">
    <meta name="keywords" content="This is gaming zone website where all type of games are display">
@endsection

@section('banner')
<h1 class="font-semibold text-white text-4xl">Terms Conditions</h1>
@endsection
@section('content')

<section class="vs-about-wrapper space-top">
    <div class="container z-index-common md:py-[120px]">
        <div class="row align-items-center flex-row-reverse justify-content-between">
          
            <div class="col-lg-12 col-xxl-12 mb-30">
                <div class="about-content ps-xxl-3 ps-xxl-5">
<h2 class="font-semibold text-xl sm:text-2xl lg:text-xl xl:text-2xl mb-10 inline-block text-dark  hover:text-primary pt-10">Terms & Conditions</h2>
                    <div class="sec-shape">
                        <div class="sec-shape_bar"></div>
                        <div class="sec-shape_bar"></div>
                        <div class="sec-shape_bar"></div>
                    </div>
                    <p class="sec-text mt-4 pt-2">Praesent a ornare metus. Etiam luctus arcu a neque venenatis, quis hendrerit mi maximus. Proin tincidunt tellus</p>
                    <div class="arrow-list mb-4 pb-2">
                        <ul>

                            <li><i class="fal fa-arrow-circle-right"></i>(“ agamefun.com ”) respects your privacy and is fully committed to protect the personal information that you share with it. agamefun.com believes that its users(the “Users”) have a full right to know its policies and practices regarding the information agamefun.com collects while using its software application (the “ agamefun.com ”).

                                Consent

                                BY USING THE SOFTWARE AND/OR BY INSTALLING THE SOFTWARE ON YOUR MOBILE PHONE YOU INDICATE YOUR ACCEPTANCE OF THE PRACTICES DESCRIBED IN THIS PRIVACY POLICY (the “Privacy Policy”).

                                Collection of information


                                “ agamefun.com ” may collect personal information provided consciously and voluntarily by you during your use of this Software. “Personal Information” means individually identifiable information collected during your use of the services provided to you by “ wpstuffy.com ”. According to the nature of the service, no information generated by the users will be available to the general public via the Internet.

                                Use of Information

                                agamefun.com may use the Personal Information in order to: manage the service (i) provide certain services; and (ii) provide customer support; (iii) send the users promotional information and advertisements. Altering of Personal Information For instructions on how to request change of any personal information you have provided agamefun.com with, please send an email to apps@agamefun.com

                                Security

                                agamefun.com takes great care in implementing and maintaining the security of User’s Personal Information. agamefun.com employs industry standard procedures and policies to ensure the safety of its Users information, and prevent unauthorized use of any such information. Among other measures, agamefun.com protects User’s Personal Information through the use ,However, agamefun.com does not guarantee that unauthorized access will never occur.

                                Questions

                                If you have any questions or comments about this Privacy Policy, please feel free to send us an email to apps@agamefun.com
                                .</li>
                        </ul>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</section>

<section class="vs-blog-wrapper space-top space-extra-bottom">

    @endsection